# Generated by Django 3.1.4 on 2020-12-20 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='external_id',
        ),
        migrations.AddField(
            model_name='book',
            name='ref',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
