# Generated by Django 3.1.4 on 2020-12-21 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20201220_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='name',
        ),
        migrations.AddField(
            model_name='rate',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.book'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
