from .distributor import DistributorAdmin
from .book import BookAdmin
from .category import CategoryAdmin
from .rate import RateAdmin
from .format import FormatAdmin
from .author import AuthorAdmin
from .like import LikeAdmin
from .language import LanguageAdmin
from .country import CountryAdmin
from .city import CityAdmin
